### ISSUE TITLE
Update php production guides

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-guides#79]
Currently all the production php guides recommend using `php-server` as web `start` commands. The problem with this approach is that runit, the process manager views the multiple processes started as a single process. If one of them dies, it won't restart it.

The better approach would be to use two separate start commands:

#### Using Apache
```yaml
web.site:
  start:
    php: start-php
    apache: start-apache
```

#### Using Nginx
```yaml
web.site:
  start:
    php: start-php
    nginx: start-nginx
```
