### ISSUE TITLE
Update rails guides to allow nokogiri to be installed

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-guides#94]
In order for nokogiri to be installed successfully, the following packages need to be included:

```yaml
run.config:
  engine: ruby
  extra_packages:
    - pkgconf
    - libxml2
    - libxslt
```
